"""empty message

Revision ID: 772ffc8ba8e4
Revises: ccc467635d94
Create Date: 2020-07-20 07:28:25.232889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772ffc8ba8e4'
down_revision = 'ccc467635d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('artists', 'seeking_talent')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
