"""empty message

Revision ID: fcaa91a2690c
Revises: 772ffc8ba8e4
Create Date: 2020-07-20 14:39:45.980204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaa91a2690c'
down_revision = '772ffc8ba8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
